name: CI

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
  lint:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba
  test_latest:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings
  test_nightly:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:nightly-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: shards build --production
      - name: Specs
        run: crystal spec --order random --error-on-warnings
